[package]
name = "crypto-bigint-dudect"
version = "0.0.0"
authors = ["RustCrypto Developers"]
publish = false
edition = "2021"

[dependencies]
clap = "2.33"
crypto-bigint = { path = ".." }
dudect-bencher = "0.5"
